### PR TITLE
Improving build speed using ccache (compiler cache), RAM disk and parallel jobs

### PR DESCRIPTION
**Pull request by oam7575**
Patches and notes to speed up rescuezilla build environment.

Exact speed up will depend on the underlying hardware, internet connection speed and the ability to use a RAMDISK for the build.

Previous builds took approximately 23 minutes on modern hardware with SSD.

Modified builds on the same hardware with cold compiler cache take approximately  9 minutes

Modified builds with hot compiler cache take approximately 6 mins 30 seconds.

YMMV

### CODE REVIEW

**Comment by shasheene** [comment]
Great work @oam7575!

**I will evaluate your changes and integrate them.**

By the way, I recommend [this guide](https://chris.beams.io/posts/git-commit/) for improving your future commit messages. The first line of a commit message can be more descriptive and useful rather than eg, "Update filename" (the files that have been modified are already listed in the git commit itself). This is the approach taken in the Rescuezilla repository already (except for the translation commits created by Weblate, which unfortunately have their own not very descriptive subject like "Translated using Weblate (German)").

Other than that, your work looks great. Excellent work, especially since it's your first Pull Request ever as far as I understand!

**Comment by oam7575** [comment]
Hey Shasheene,

Thanks for the feedback, fair call regarding the commit message.
I'm hardly a coder, have limited hands on with git / committing code and a bit rough with everything else.

I'd be interested to see how (if) it all runs on whatever hardware you are using to build everything, before and after performance times etc.

**Comment by shasheene** [comment]
OK @oam7575, I have evaluated your changes and have integrated them most of them.

Here are some benchmarks (all testing done with a Docker container). I have used the bash builtin “time” to measure the results. I only list the “real” number produced by the command, because that’s the wallclock time.  See `help time` for more information. All commands have a populated debootstrap pkg.cache folder (ie `make clean-all` was NOT run), to remove (most of) the internet speed part from the equation.

**Before your changes**:
`make clean` followed by `time make focal`: 18m30s
**After your changes except gzip/netselect (see below)**
`make clean` followed by `time BASE_BUILD_DIRECTORY=/mnt/ramdisk make focal`: 10m11s
**After your changes except gzip/netselect plus my debug mode low compression change (see below)**
`make clean` followed by `time BASE_BUILD_DIRECTORY=/mnt/ramdisk IS_INTEGRATION_TEST=true  make focal`: 6m6s

** What I didn’t implement **
I didn’t include your gzip/pigz change because I couldn’t see any improvement. Here’s my adaptation. You may want to confirm it doesn’t help. You can do this by running `git remote add shasheene-dev https://github.com/shasheene/rescuezilla-dev; git fetch shasheene-dev`; git checkout remaining-oam7575-build-speedups`.

I also didn’t implement your configure_mirror.sh as running your netselect command by itself seemed to output a number rather than the correct URL.

**New changes I made**

You may remember previously [suggested](https://github.com/rescuezilla/rescuezilla/issues/161) switching the mksquashfs to use zstd with compression level 10 for a smaller image, but I chose compression level 19 for much better compression ratios and similar decompression at the expense of much slower compression speed. I did some tests:

Currently used in official ISOs: Zstd compression 19. On my machine with 4 threads: 4m3s

Compared to: Zstd compression level 1: 0m13s

This is really great, because fast builds are often very useful in development. I have added this behind a debug. Build with `IS_INTEGRATION_TEST=true make` to get it. Also in addition to [the low compression, the IS_INTEGRATION_TEST flag enables an SSH server for general test/debug and [integration test suite purposes](https://github.com/rescuezilla/rescuezilla/blob/master/src/integration-test/README.md#preparing-rescuezilla-iso-image).

Thanks again, these build speed improvements are VERY useful. Especially now that you and I are introducing a large number new ISO images into Rescuezilla.

Also as mentioned above, each build will be run against the [Rescuezilla Integration Test Suite](https://github.com/rescuezilla/rescuezilla/blob/master/src/integration-test/README.md), so all the build speeds improvements are are very important.

We can discuss the gzip and netselect changes here before closing this PR.

**Comment by oam7575** [comment]
Hi Shasheene,

I'll double check the pigz settings and the netselect / configure_mirror.
I probably made a mistake somewhere between what I tested and what I uploaded.

With that said - due to the somewhat messy nature of my changes - I would be happy with ; and its probably cleaner for me to 
* close this PR
* Rebase to your current master
* Check the pigz / netselect code
* create new PR 

Either way I'll run some tests and get back to you.

**Comment by shasheene** [comment]
Sounds good I'll close this PR.

Remember to build with `IS_INTEGRATION_TEST=true ./build.sh` to get the fast mksquashfs compression.

So rebasing onto the current master will bring a whole lot of conflicts that need to be resolved (using manual editing followed by `git add <filename>` then `git rebase --continue`). But resolving it won't be that useful.

Instead, the simplest way to do this is as follows:
```
# Ensure you're on your local master branch
git checkout master
# Backup the changes
git branch oldMaster
# Fetch master branch of this GitHub rescuezilla/rescuezilla remote
git fetch origin
# Reset your local master to the latest changes
git reset --hard origin/master
# Manually apply your pigz change
git cherry-pick 6ad4b41e8deb2e7d66be6730a2eecf4fd6ad1ab1 54d573168eea3fdc28b36a1050ca6f91b4618d07
# Manually apply your netselect change
git cherry-pick d9978f6139f831e8c9c8ce6e3a27aff440ac7499 130fe5d7e971e43494b5c1ea90d6d947d315e1f0
```
The last cherry-pick has a conflict on  the second commit. So you need to manually fix the build instructions doc conflict then use 
```
git add docs/build_instructions/BUILD.ISO.IMAGE.md`
git cherry-pick --continue
```

After this your 4 remaining patches will be applied on origin master. Perfect!

But you may want to do a _interactive_ rebase (`git rebase -i`) to **squash** the second and fourth commit into the first and third commit for a cleaner git history:

```
pick <commit_sha> Update chroot.steps.part.1.sh
s <commit_sha> Update chroot.steps.part.2.sh
pick <commit_sha> Create configure_mirror.sh
s <commit_sha> Update BUILD.ISO.IMAGE.md
```

I recommend the tool tig (`sudo apt-get install tig`) as a way to look at git history nicely.

**Comment by shasheene** [comment]
I have edited the previous comment to provide more advice on the advanced concept of interactive git rebasing.

Even if you choose not to pursue interactive rebasing, I highly recommend tig (`sudo apt-get install tig`) to view git history.

**Comment by oam7575** [comment]
TL-DR:
* The HOST CPU core speed appears to be the largest factor in build times.
* Swapping Zstd compression from 19 to 1 ; is the second largest factor - all other improvements were minor in comparison.
* Pigz inside chroot doesnt appear to do much.
* Pigz configured at VM build host level appears to make a bit of an improvement.

Using the current (2021-09-11) Rescuezilla master for build tests carried out inside a virtual machine.
Using Ram disk option to remove and disk latency
Using apt-cacher-ng on local network to remove as much download delay as possible.
Execute sudo make clean-all between each build.

7 Tests were carried out.
Some tests were run twice
Fastest result at the bottom

**Details**

HOST: Ryzen 3600  - 6 cores 12 threads
RAM : 16 Gb
OS : Win 10 x64

VM Guest - 12 vCORES
RAM : 8Gb
OS : Ubuntu 20.04 
Using
Local network apt-cache-mirror
7Gb ram disk

Clean copy of rescuezilla from master.

**Test 1**
sudo time make focal

real    13m33.604s
user    31m36.270s
sys     6m17.183s

fast

**Test 2**
zstd - comp = 1 
manual edit the build.sh file to keep all other build commands the same.

sudo time make focal

real    10m22.438s
user    11m4.510s
sys     5m8.220s


**Test 3**
zstd - comp = 1  : as per Test 2
Plus switch VM Guest from gzip to pigz 

mv /bin/gzip /bin/real_gzip
update-alternatives --install /bin/gzip gzip /bin/pigz 100
update-alternatives --install /bin/gzip gzip /bin/real_gzip 50

sudo time make focal

real    9m36.991s
user    8m44.272s
sys     4m33.295s


**Test 4**
As per Test 3
Plus add pigz configuration to the chroot Rescuezilla build.
as per pervious patches to chroot.steps.part.1.sh

sudo time make focal
real    9m39.042s
user    8m36.308s
sys     4m38.167s **** extra time probably due to installing pigz ***



**Test 5**
As per Test 4
switch linux-generic-hwe from 18.04 to 20.04
( required download )

real    9m51.346s
user    8m4.307s
sys     4m29.903s


**Test 6** 
As per Test 5
HWE kernel downloaded and cached.
force initramfs to gzip 

Run 1
real    9m15.355s
user    8m20.169s
sys     4m30.432s

Run 2
real    9m20.646s
user    8m23.705s
sys     4m34.802s


**Test 7**
as per Test 6
no changes in VM 
Force DISABLE Windows HOST power managment.
Effecively forcing HOST CPU to 100% cpu speed and remove throttling.
core speed ~3.17Ghz ; when throttling core speed ~1.69Ghz 
Core speed approx twice as fast, hence build approx twice as fast.

Run 1
real    5m4.241s
user    4m29.663s
sys     2m32.387s

Run 2
real    5m2.267s
user    4m26.850s
sys     2m30.921s

**Comment by oam7575** [comment]
I tested the configure_mirror script.
It appears to be working on my side.

The netselect package needs to be installed and it needs to run as root / via sudo.
Netselect is not available in Ubuntu 20.04 by default - so the script attempts to download directly from Debian FTP and then install it.
it then attempts to parse the Ubuntu mirror list and pick the fastest one depending on your internet routing etc.

Not strictly needed; and  for anyone looking to build more than once I would suggest a caching server anyways.

**Comment by shasheene** [comment]
Thanks for the information. I am happy to skip the gzip/pigz build script change since the benefits don't seem worth it.

I'm not too concerned with the network speed issues personally, as I have a 1000mbps connection. Also I find the caching does really well: apt-get update happens every time, but packages stay under the pkg-cache folder even if running `make clean` (but not `make clean-all`).

By the way, I think saw somewhere that you are also based in Australia. I**f so, I highly recommend getting a free quote on the [NBN Technology Choice Program Online Calculator](https://www.nbnco.com.au/learn/technology-choice-program/online-quote).**

I upgraded by FTTC NBN connection to Fibre To the Premises quote $3000 upgrade. An FTTN->FTTP upgrade tends to be quoted at $10,000 (but will likely be upgraded free in the coming years, unlike FTTC). For me, upgrading FTTC->FTTP for $3000 was a no-brainer. After paying and waiting a long 6 months to get the fibre installed and activated I went from getting 60mbps speeds to to 900+mbps speeds by paying only $20 a month more to my ISP.

**Even if you don't intend to upgrade, it's worth filling in the free online calculator linked above (and linking it to those you know).** 1000mbps connections are amazing :)

**Comment by oam7575** [comment]
You are correct - in Australia.
Currently on FTTN ( VDSL2 last mile )
On a 50/20 plan - router suggests I might be able to get close to ~95mbits if I changed plans.

Paying for an upgrade to FTTP is somewhat cost prohibitive.
This WP  thread : https://forums.whirlpool.net.au/thread/97wjj0k9?p=1131
has a link to this Google Docs spreadsheet : https://docs.google.com/spreadsheets/d/e/2PACX-1vS4A3OuN9GCIInzbaWr9OOl0dEUUyPgIuWT2zousCS8dSEAbFdFBaQB5P3pSGpfKEBH1ue7T6Baemvu/pubhtml

Australian Gov and NBN Co apparently have a plan to selectively upgrade certain areas from "what ever" to FTTP depend in on end user request and plan change. 

Currently waiting to see which way the wind blows.

**Comment by shasheene** [comment]
Yes, FTTN is definitely too expensive using TCP (more than $10k). I am lucky my area got FTTC rolled out.

I'd be impressed if you'd be able to get 95mbps using FTTN and VDSL2. Maybe if or when they rollout G.fast instead of VDSL2.

But yes, there is talk of certain FTTN areas being upgraded to FTTP for free. I agree you're best bet is waiting at this stage.

**Comment by oam7575** [comment]
Hi Shasheene,

Final comment on this thread - but it's related so seemed to be the best spot for it.
In Hirsute and newer; Kernel 5.11 and newer ( possibly others ? ) supports switch to ZSTD for mkinitramfs

real    4m29.402s
user    6m1.839s
sys     1m59.331s

Using the same configuration as Test 7 above;  build but switching initramfs.conf to zstd shaves about 30 seconds off previous best build times.

Should make the ISO boot faster also.

Using zstd ISO boots a vmware workstation no problem ..
Having problems with my PXE environment - seeing "can't open /dev/sr0 no medium found" 
Have not tested boot from USB.

**Comment by shasheene** [comment]
Sounds great! 

gzip and zstd should _decompress_ at the approximately the same rate by the way, so boot may not be faster.

If the option is there, I will increase the compression on the standard build to level 19 (and level 1 when using the debug flat `IS_INTEGRATION_TEST`). For official release builds, the slower build, but better compression ratios is well worth it.

I will also ensure zstd is only used for newer kernels, as I hope to reintroduce a i386 version based on Bionic not just Debian 11.

Feel free to push any work you have onto your private fork's branches and I can examine them. No need to make a new pull request. You can reference this issue in your pull request by just typing "Ref #245" in the commit message. Note that "#" is the comment character if placed at the start of a line.

**Comment by oam7575** [comment]
The zstd setting in initramfs appears to default to level 19.
Was unable to see any setting to change it

**Pull request closed without merging**
