### PR TITLE
Implement VNC server and Build system speed up 

### PR DESCRIPTION
**Pull request by oam7575**
This pull request implements previously created multithreaded speed up
https://github.com/rescuezilla/rescuezilla/issues/7

and also implements changes to configure an x11vnc server to automatically start when the system is booted.
https://github.com/rescuezilla/rescuezilla/issues/11

### CODE REVIEW

**Comment by shasheene** [comment]
Most changes in this PR have been adapted and merged as part of #245.

Running a VNC server as root user is dangerous from a security perceptive, even if password protected. It's possible to run it as the Ubuntu user, which is better.

But the broader issue is running network-connected background processes (that many users will not use) isn't a good idea from a security pespective. Ideally a background service would be only started if the user requests it (eg, click icon on desktop), but that's not possible here as VNC is used for headless systems.

I still don't have an ideal solution on how to best integrate a VNC server into Rescuezilla

**Comment by oam7575** [comment]
Hi Shasheene,

I agree with your concerns / issues regarding running VNC as root; I certainly should have been more clear regarding its configuration in my notes.

The reason for that configuration is that it appears the desktop manager and Rescuezilla itself are running as root user.
As an addition to that the idea / intent was to provide for the possibility of a headless PXE boot with remote control.

This should be considered a starting point for that ( what programs and changes are required to have VNC function ) - and not a finished version.

As you say VNC should not be running as root, or at least not directly exposed to the network.
Ideally I would like to have SSH installed; along with some form of user configurable persistent local storage.

If those two features were available it would then be possible to use Private / Public key pairs for SSH authentication and access the VNC service via SSH tunnel without exposing it directly to the network.

As an aside; it could be argued that a product like Rescuezilla / Clonezilla and having a PXE service that serves up those products on an untrusted / open network would be a bad idea at any rate.

Finally you are correct regarding the speed up builds... I am currently manually managing my file changes on this side and rolled them all in together again when I rebased my rescuezilla master to your current / master at that point in time.


Once again - to be used as a starting point for ideas and further development - happy to discuss / change / discard as needed.

**Comment by interduo** [comment]
When this PR will be merged?
VNC on bootup would be very useful! :)

**Comment by shasheene** [comment]
As mentioned in an earlier comment, running a VNC on bootup would change Rescuezilla's security profile.

The VNC server has to be manually able to be started somehow. But without a display, what's the best way to do this?

**Comment by interduo** [comment]
> Rescuezilla's security profile.

In my opinion its no problem when:
- the access would be restricted to local area network,
- You know about that and You could stop optionaly VNC somehow from UI,

**Pull request closed without merging**
