### PR TITLE
Jammy 22.04 support

### PR DESCRIPTION
**Pull request by regs01**
It needs a symlink in debootstrap. Don't know how to make it with GitHub online editor. I guess there could be problems with focal now. May be some different packages. May be not.

Ideally would be better to have separate package list for each system, if maintaining support of several systems.

### CODE REVIEW

**Comment by regs01** [comment]
I guess having support of older formats is good, so `partclone.restore.v0.2.43.amd64` needs to get a look by some c++ pro.

**Comment by regs01** [comment]
Firefox is not longer part of Ubuntu repository. It's not possible to use snapd in chroot, so `ppa:mozillateam/ppa` might be an option.

**Comment by shasheene** [comment]
Yeah I ran into that same issue before, where [snaps aren't supported in chroots](https://bugs.launchpad.net/snappy/+bug/1609903). I made a comment on that thread 2 years ago, and I see you did just recently too.

Switching to another browser (Chromium), or switching Rescuezilla entirely to Debian are both good approaches. I will take a look this weekend.

**Comment by regs01** [comment]
I'm still for Firefox. It's just better. Using PPA isn't a bad option. Still having snaps would be good. Someone said it needs a compact version. I'm thinking otherwise and making an option of larger set of apps for wider administering and recovery capabilities.

**Comment by shasheene** [comment]
Thanks again for your PR from 2 months ago..

I have taken your advice for adding Firefox through the Mozilla Team PPA **and merged the changes as part of a new PR #339**, because I didn't have push permissions onto the GitHub branch you used to create this PR.

**Pull request closed without merging**
